SPM parser config is now external
bids-standard/BEP028_BIDSprov pull request #54
Opened 2021-03-12 09:46 UTC by remiadon

config in separate file : `bids_prov/spm_config.py`

2021-03-12 13:34 UTC, cmaumet requested changes
Thanks @remiadon! 

Here are a few comments for updates to be made before we can merge:
 - Please include a description in the top comment of this PR, this will ensure that we have appropriate documentation for the project. 
 - Where are the configuration files stored? As far as I can see, they are not in this PR?

2021-03-12 14:44 UTC, remiadon commented
@cmaumet there are no configuration files stored. This is the SPM parser, everything lies in the `spm_config.py` file

2021-03-16 13:29 UTC, remiadon reviewed
@cmaumet la partie DEPENDENCY_DICT a bien été incluse dans le nouveau fichier `spm_config.yml`

2021-03-29 09:50 UTC, remiadon commented
@cmaumet j'ai fait un premier exemple avec l'activité "segment"

Voici le nouveau graphe 
![test](https://user-images.githubusercontent.com/2931080/112819184-9b44eb00-9084-11eb-9187-6fa5a2dfa663.png)

Plusieurs questions:
 - Je remplace le nom de l'activité dans le graphe par celui spécifié dans la config ? (eg. `spatial.preproc` --> `segment`). Si c'est le cas 
 - Comment remplir le champ `prov:atLocation` ? On mets de chemins en fixe

J'espère que c'est bien ce format là que tu attends

2021-04-02 13:23 UTC, remiadon commented
![test](https://user-images.githubusercontent.com/2931080/113419162-31e81380-93c7-11eb-847f-a83d6910c8ee.png)
@cmaumet voici le graphe que j'obtiens en lançant `python -m bids_prov.spm_parser examples/spm_default/batch.m -o test.json && python bids_prov/visualize.py --omit-details test.json && open test.png` depuis la racine

2021-04-02 13:26 UTC, cmaumet commented
Ok - as-tu vérifié si la dépendance qui se trouve [ici](https://github.com/incf-nidash/nidmresults-examples/blob/master/spm_default/batch.m#L91) est bien retrouvée par ton code [ici](https://github.com/bids-standard/BEP028_BIDSprov/pull/54/files#diff-16aa352f4728b674b0486a2843bda76bea3d8dee8cf38d2e7a59768a8b41d04aR136) ? Par exemple en ajoutant un `print(dependency)` pour voir quelles sone les dépendences qui sont bien trouvées ?

2021-04-02 13:41 UTC, remiadon commented
@cmaumet  oui il y est bien

2021-04-02 13:45 UTC, cmaumet commented
Très bien ! Et est-ce que le lien "used" est bien créé [ici](https://github.com/bids-standard/BEP028_BIDSprov/blob/56c71878ab550637d2fe340112f1551cfd07d946/bids_prov/spm_parser.py#L150)? Si oui, avec quelle activité ?

2021-04-02 15:02 UTC, remiadon commented
@cmaumet le lien "used" est mauvais, cf ici https://github.com/bids-standard/BEP028_BIDSprov/blob/56c71878ab550637d2fe340112f1551cfd07d946/bids_prov/spm_parser.py#L150

la variable "output_id" n'est peut etre pas le bon id ....

2021-04-26 09:29 UTC, cmaumet commented
Remi: I think I've found a solution. The link created by the line you mentioned above was correct but then it was overwritten at: https://github.com/bids-standard/BEP028_BIDSprov/blob/56c71878ab550637d2fe340112f1551cfd07d946/bids_prov/spm_parser.py#L171-L172

I've proposed a fix to instead merge the two lists (cf. https://github.com/bids-standard/BEP028_BIDSprov/pull/54/commits/0b24cabb85c8f8cd3ccbb2c5af3222e6e25fb60f) and now the link between "smoothed images" and "fmri_spec" is no longer missing. 

![test](https://user-images.githubusercontent.com/5374264/116060847-8313bc00-a682-11eb-8e3c-99023ff98b58.png)

2021-04-26 09:38 UTC, merged